const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

const root = join(__dirname, '..');
const app = readFileSync(join(root, 'App.tsx'), 'utf8');
const live = readFileSync(join(root, 'src/screens/LiveScreen.tsx'), 'utf8');
const exploreHome = readFileSync(join(root, 'src/components/explore/ExploreHomeView.tsx'), 'utf8');
const discoveryPlace = readFileSync(join(root, 'src/components/explore/DiscoveryPlaceSheet.tsx'), 'utf8');
const narrativeOverlay = readFileSync(join(root, 'src/components/explore/NarrativeOverlay.tsx'), 'utf8');
const guidedNavigation = readFileSync(join(root, 'src/components/explore/GuidedNavigationView.tsx'), 'utf8');
const transcript = readFileSync(join(root, 'src/components/explore/TranscriptSheet.tsx'), 'utf8');
const tourPreferences = readFileSync(join(root, 'src/components/explore/TourPreferencesSheet.tsx'), 'utf8');
const history = readFileSync(join(root, 'src/screens/HistoryScreen.tsx'), 'utf8');
const settings = readFileSync(join(root, 'src/screens/SettingsScreen.tsx'), 'utf8');
const guideProfile = readFileSync(join(root, 'src/components/explore/GuideProfileModal.tsx'), 'utf8');
const routing = readFileSync(join(root, 'src/context/appIdentity.ts'), 'utf8');
const liveSurface = [live, exploreHome, guidedNavigation, transcript, tourPreferences].join('\n');

assert.match(routing, /return 'Main';/, 'first launch routes to Main/Explore');
assert.match(app, /name="Explore"/, 'Explore tab is present');
assert.match(app, /name="Stories"/, 'Stories tab is present');
assert.match(app, /name="Settings"/, 'Settings tab is present');
assert.doesNotMatch(app, /name="Drive"/, 'Drive is not a bottom tab');
assert.match(app, /hey-city-navigation-welcome-v2/, 'UI update remounts stale navigation state');

assert.match(live, /mode !== 'city_explorer'.*sessionId/s, 'Explore starts a real discovery session');
assert.match(live, /aheadTarget\.providerId/, 'Explore renders the selected Ahead Discovery target');
assert.match(live, /aheadDiscovery\?\.topCandidates/, 'Explore renders only backend discovery candidates');
assert.match(liveSurface, /showsUserLocation/, 'Walking Mode keeps the user visible on the map');
assert.match(liveSurface, /walking\.searchPlaceholder/, 'Walking Mode has a real guided-walk entry action');
assert.match(liveSurface, /onOpenGuide/, 'Walking Mode guide portrait opens the guide surface');
assert.match(exploreHome, /onSelectPlace/, 'Walking POI cards and markers open a place surface');
assert.match(discoveryPlace, /MapView/, 'Place surface contains an accurate map preview');
assert.match(live, /destination_place_id/, 'Place surface can open a real Google Maps route');
assert.match(live, /backendWalkingStoryVisible/, 'Walking Mode renders backend story playback state');
assert.match(live, /lastResult\?\.transcriptText/, 'Walking story and transcript use backend narrative text');
assert.match(narrativeOverlay, /onSkip/, 'Walking story player exposes a real skip action');
assert.match(exploreHome, /statusBanner/, 'Walking Mode renders a consumer-facing degraded state');
assert.match(live, /onRetry=.*startSession/s, 'Walking degraded state retries the real discovery session');
assert.doesNotMatch(exploreHome, /region=\{region\}/, 'Walking map is not locked by a controlled region');
assert.match(live, /scrollEnabled=\{!mapFirstForeground\}/, 'Walking and guided maps are not trapped in a scrolling parent');
assert.match(live, /returnTo: 'explore'/, 'Walking guide preview returns to the map');
assert.match(liveSurface, /Start your walk/, 'Tour Preferences surface exists');
assert.match(live, /guideProfileOpen/, 'Guide Profile surface exists');
assert.match(liveSurface, /choose up to 3|Choose up to 3 interests/, 'Interest limit guard exists');
assert.match(liveSurface, /No interests selected/, 'Zero-interest fallback exists');
assert.match(liveSurface, /Transcript/, 'Transcript access exists');
assert.match(live, /End tour\?/, 'End Tour confirmation exists');
assert.match(liveSurface, /topChip/, 'Navigating state has top destination chip');
assert.match(live, /Share Route/, 'Share Route action exists');
assert.match(live, /No account required to start/, 'Share Preview guest microcopy exists');
assert.match(live, /invalid_link/, 'Share Preview invalid-link state exists');
assert.match(live, /unsupported_location/, 'Share Preview unsupported-location state exists');

assert.match(history, /Your City Stories|history\.title/, 'Stories title is consumer-facing');
assert.match(history, /Start your first walk/, 'Stories empty state is not blank');
assert.match(history, /MapView/, 'Stories cards use a route thumbnail');

assert.match(settings, /Guide & Interests/, 'Settings has Guide & Interests');
assert.match(settings, /Audio & Text/, 'Settings has Audio & Text');
assert.match(settings, /History & Privacy/, 'Settings has History & Privacy');
assert.match(settings, /About Hey City/, 'Settings has About Hey City');
assert.match(settings, /Switch value disabled/, 'Settings does not expose inert audio controls as active');
assert.match(settings, /nestedScrollEnabled/, 'Settings explicitly enables nested scrolling');
assert.match(settings, /alwaysBounceVertical/, 'Settings exposes vertical scrolling on iOS');
assert.match(settings, /flexGrow: 1/, 'Settings content owns a full-height scroll surface');
assert.match(settings, /Welcome v2 · Settings scroll v2/, 'Settings exposes the current UI build marker');
assert.match(settings, /setGuideProfileOpen\(guide\.id\)/, 'Settings guide images open the full profile');
assert.match(guideProfile, /PanResponder\.create/, 'Full guide profile supports horizontal swipe');
assert.match(guideProfile, /voiceSampleLabel/, 'Full guide profile exposes a voice sample placeholder');
assert.match(guideProfile, /borderRadius: radius\.sm/, 'Full guide profile avoids pill-shaped primary controls');
assert.doesNotMatch(guideProfile, /backgroundColor: 'rgba\(0,0,0/, 'Full guide profile does not cover the portrait with a dark overlay');

console.log('citySignalUiContract tests passed');
