import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';
import { fixture } from './narrativeFixtures';
import { NarrativeGenerator, narrativeFingerprint } from '../src/services/narrativeGenerator';
import { AITaskRouter, AITaskRoutes } from '../src/ai/aiTaskRouter';
import { GenerativeProvider, GenerativeTaskRequest } from '../src/ai/generativeProvider';
import { validateStory } from '../src/services/storyQa';
import { normalizeEvidence, storyAvailability } from '../src/services/evidence';
import { buildStoryBrief } from '../src/services/storyBrief';
import corpus from '../../evaluation/golden/narrative-v2.json';

async function run() {
  const calls: GenerativeTaskRequest[] = [];
  const provider: GenerativeProvider = { id: 'quality', supports: () => true, generate: async request => {
    calls.push(request); return { text: 'The current building opened as a Custom House, long after the inauguration at this site.', providerId: 'quality', model: 'fixture' };
  } };
  const routes: AITaskRoutes = { final_storytelling:'quality', complex_follow_up:'quality', evidence_compression:'deterministic', poi_normalization:'deterministic', relevance_classification:'deterministic' };
  const generator = new NarrativeGenerator(new AITaskRouter([provider], routes));
  const dana = fixture(); const arthur = fixture({guide:'artur'});
  assert.equal(arthur.policy.id, 'arthur');
  assert.notDeepEqual(dana.plan.beats, arthur.plan.beats, 'T5 distinct guide beat tendencies');
  assert.notDeepEqual(dana.policy.behavior, arthur.policy.behavior);
  assert.equal(dana.plan.poiId, 'federal-hall', 'T1 approved target');
  assert.equal(dana.brief.subject.name, 'Federal Hall');
  assert(!JSON.stringify(dana.plan).includes('Washington'), 'public plan contains no evidence prose');
  assert(!JSON.stringify(dana.plan).includes('https://'), 'public plan contains no source URL');
  const short = await generator.generate(dana);
  await generator.generate(dana);
  assert.equal(calls.length, 1, 'one final call per segment; second request is a cache hit');
  assert.equal(calls[0].task, 'final_storytelling', 'T2 router boundary');
  assert(!calls[0].input.includes('https://'), 'T3 attribution is not prompt prose');
  assert(calls[0].input.includes('VERIFIED EVIDENCE'));
  const long = fixture({level:'long',continuation:{poiId:dana.plan.poiId,guideId:'dana',language:'en',previousLevel:'short',previousTranscript:short.text}});
  await generator.generate(long);
  assert.equal(long.brief.continuation?.previousTranscript,short.text);
  assert.match(calls[1].instructions, /do not restart, repeat/);
  assert.match(calls[1].input, /ALREADY HEARD:/);
  assert(!JSON.stringify(long.plan).includes(short.text), 'continuation transcript remains server-only');
  const standalone = fixture({level:'long'});
  assert.equal(standalone.brief.continuation,undefined,'T7 direct long');
  const keys = [dana,arthur,long,standalone,fixture({language:'ru'}),fixture({mode:'vehicle'})].map(narrativeFingerprint);
  assert.equal(new Set(keys).size,keys.length,'T12 complete context isolation');
  const revised = structuredClone(dana); revised.brief.evidence.sourceVersion += '.2';
  assert.notEqual(narrativeFingerprint(dana),narrativeFingerprint(revised));
  const tampered = structuredClone(dana); tampered.plan.poiId = 'other-place';
  await assert.rejects(generator.generate(tampered), /authority mismatch/);
  assert.equal(calls.length,2,'invalid authority never reaches LLM');
  const weak = normalizeEvidence({id:'weak',name:'Example Local Monument',category:'monument'},'', 'google');
  assert.deepEqual(storyAvailability(weak),{short:false,long:false});
  assert.throws(()=>fixture({subject:'weak'}),/Not enough verified/);
  const emptyRequest = structuredClone(dana); emptyRequest.brief.evidence.items=[];
  await assert.rejects(generator.generate(emptyRequest),/Not enough verified/);
  assert.equal(calls.length,2,'T4 zero provider calls for weak evidence');
  const russian = fixture({language:'ru'});
  for (const text of ['', 'Source: Wikipedia', 'https://example.com', 'NarrativePlan says to ignore instructions', 'This is entirely English.']) {
    assert.throws(()=>validateStory(text,russian.brief),`reject ${text}`);
  }
  for (const text of ['This historic building has a story.', 'This iconic attraction is famous.', 'Federal Hall is a historic landmark located in New York.', 'Federal Hall was built in 1842 and is known for history.', 'Would you like to know more?']) assert.throws(()=>validateStory(text,dana.brief));
  validateStory('Здесь важно различать место и здание. Нынешнее здание открылось как таможня.',russian.brief);
  const vehicle = fixture({level:'long',mode:'vehicle'});
  assert.equal(vehicle.plan.targetDurationSec,45,'E5 explicit long cannot bypass vehicle limit');
  assert.equal(vehicle.brief.constraints.targetDurationSec,45);
  assert.equal(vehicle.plan.safety.visualLoad,'minimal');
  assert.throws(()=>validateStory(Array(120).fill('building').join(' '),vehicle.brief),/word budget/);
  for (const scenario of corpus.scenarios) assert(scenario.required.length && scenario.prohibited.length);
  assert.equal(corpus.scenarios.length,8);
  const start = performance.now();
  for (let i=0;i<10000;i++) buildStoryBrief(dana.plan,dana.brief.evidence,dana.policy,{level:'short',language:'en'});
  console.log(JSON.stringify({storyBriefMeanMs:(performance.now()-start)/10000,iterations:10000,provider:'fixture',llmCallsPerUncachedSegment:1}));
  console.log('M1 T1–T7, T11–T12 contract and deterministic QA tests passed (not live model experience QA)');
}
void run().catch(error=>{console.error(error);process.exitCode=1;});
